# Exported from Render on 2026-03-17T22:50:45Z
version: "1"
projects:
  - name: Grove API
    environments:
      - name: Production
        services:
          - type: web
            name: webhook-discord-bot-ruv6
            runtime: node
            repo: https://github.com/render-examples/webhook-discord-bot
            plan: starter
            envVars:
              - key: DISCORD_CHANNEL_ID
                sync: false
              - key: DISCORD_TOKEN
                sync: false
              - key: RENDER_WEBHOOK_SECRET
                sync: false
              - key: RENDER_API_KEY
                sync: false
            region: oregon
            buildCommand: pnpm install && pnpm run build
            startCommand: pnpm run start
            autoDeployTrigger: commit
